CREATE TABLE [dbo].[EMP_ANSWER]
(
[ID] [uniqueidentifier] NOT NULL,
[QUESTION_ID] [uniqueidentifier] NULL,
[EMPLOYEEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE] [datetime] NULL,
[ANSWERID] [int] NULL,
[NOTE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMP_ANSWER] ADD CONSTRAINT [PK_EMP_ANSWER] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMP_ANSWER] ADD CONSTRAINT [FK_EMP_ANSWER_Employee] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[Employee] ([EmployeeID])
GO
ALTER TABLE [dbo].[EMP_ANSWER] ADD CONSTRAINT [FK_EMP_ANSWER_QUESTION] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[QUESTION] ([ID])
GO
