CREATE TABLE [dbo].[CONTRACT_SUB]
(
[ID] [uniqueidentifier] NOT NULL,
[CONTRACTID] [uniqueidentifier] NULL,
[SUBNAME] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTENT] [varbinary] (max) NULL,
[PERIODID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE] [datetime] NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEL] [bit] NULL,
[PLANT] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRACT_SUB] ADD CONSTRAINT [PK_CONTRACT_SUB] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRACT_SUB] ADD CONSTRAINT [FK_CONTRACT_SUB_CONTRACT] FOREIGN KEY ([CONTRACTID]) REFERENCES [dbo].[CONTRACT] ([ID])
GO
ALTER TABLE [dbo].[CONTRACT_SUB] ADD CONSTRAINT [FK_CONTRACT_SUB_Employee] FOREIGN KEY ([USER_CREATE]) REFERENCES [dbo].[Employee] ([EmployeeID])
GO
ALTER TABLE [dbo].[CONTRACT_SUB] ADD CONSTRAINT [FK_CONTRACT_SUB_PERIOD] FOREIGN KEY ([PERIODID]) REFERENCES [dbo].[PERIOD] ([PERIOD_ID])
GO
