CREATE TABLE [dbo].[CONTRACT_TYPE]
(
[CONTRACT_TYPE_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTRACT_TYPE_NAME] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRACT_TYPE] ADD CONSTRAINT [PK_CONTRACT_TYPE] PRIMARY KEY CLUSTERED  ([CONTRACT_TYPE_ID]) ON [PRIMARY]
GO
